export { default as Header } from "./header"
export { default as Clients } from "./clients"
export { default as About } from "./about"
export { default as Hiring } from "./hiring"
export { default as Services } from "./services"
